---
title: "Assignment 2 Code FDM"
author: "Lucas Johan Boesen"
date: Sys.Date()
output: html_document
params:
  save_plots: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(dplyr)
library(matlib)
source(paste0(getwd(), "/helper_functions_fdm.R"))
```

# FD1 

## TESTING FOR steps
## European
```{r}
true_sol_eu <- c(3.844, 3.763, 6.711, 7.700, 
                 2.852, 2.991, 5.834, 6.979,
                 2.066, 2.356, 5.060, 6.326,
                 1.465, 1.841, 4.379, 5.736,
                 1.017, 1.429, 3.783, 5.202)

time_steps <- c(200, 300, 400)
x_steps <- c(600, 700, 800, 900, 1000)
grid_test <- expand.grid(time_steps, x_steps)
diff <- rep(0, (grid_test[,1] %>% length()))

for(k in 1:(grid_test[,1] %>% length())){
spots <- c(36, 38, 40, 42, 44)
S <- c(36, 38, 40, 42, 44); col_names <- c("S", "sigma", "2", "1")

cn_02 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = grid_test[k, 1], x_steps = grid_test[k, 2], sigma = 0.2, K = 40, spots = spots)
cn_04 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = grid_test[k, 1], x_steps = grid_test[k, 2], sigma = 0.4, K = 40, spots = spots)

cn_02 <-  cbind(S, c(rep(0.2, 5)), cn_02)
cn_04 <-  cbind(S, c(rep(0.4, 5)), cn_04)
colnames(cn_02) <- col_names;
colnames(cn_04) <- col_names;
cn_all <- rbind(cn_02, cn_04) %>% 
  as_tibble() %>% 
  arrange(S) %>% 
  tidyr::pivot_longer(cols = c(`1`, `2`), 
                      names_to = "T",
                      values_to = "Finite Difference - Crank Nicolson (European)") 

diff[k] <- abs(cn_all$`Finite Difference - Crank Nicolson (European)` - true_sol_eu) %>% mean()
}

diff <- diff %>% as_tibble() %>% bind_cols(1:(grid_test[,1] %>% length())) %>% arrange(value)
print(diff)
timestep_eu <- grid_test[diff[1,2] %>% pull(), 1]
xsteps_eu <- grid_test[diff[1, 2] %>% pull(), 2]
cat("Best value: ", "time steps: ", grid_test[diff[1,2] %>% pull(), 1] , " x steps: ", grid_test[diff[1, 2] %>% pull(), 2])
```

## American
```{r}
# Using Crank_Nicolson
true_sol_us <- c(4.478, 4.840, 7.101, 8.508,
                 3.250, 3.745, 6.148, 7.670,
                 2.314, 2.885, 5.312, 6.920,
                 1.617, 2.212, 4.582, 6.248,
                 1.110, 1.690, 3.948, 5.647)
diff <- rep(0, (grid_test[,1] %>% length()))
for(k in 1:(grid_test[,1] %>% length())){
spots <- c(36, 38, 40, 42, 44)
S <- c(36, 38, 40, 42, 44); col_names <- c("S", "sigma", "2", "1")

cn_02 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = grid_test[k, 1], x_steps = grid_test[k, 2], sigma = 0.2, K = 40, spots = spots)
cn_04 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = grid_test[k, 1], x_steps = grid_test[k, 2], sigma = 0.4, K = 40, spots = spots)

cn_02 <-  cbind(S, c(rep(0.2, 5)), cn_02)
cn_04 <-  cbind(S, c(rep(0.4, 5)), cn_04)
colnames(cn_02) <- col_names;
colnames(cn_04) <- col_names;
cn_all <- rbind(cn_02, cn_04) %>% 
  as_tibble() %>% 
  arrange(S) %>% 
  tidyr::pivot_longer(cols = c(`1`, `2`), 
                      names_to = "T",
                      values_to = "Finite Difference - Crank Nicolson (American)") 

diff[k] <- abs(cn_all$`Finite Difference - Crank Nicolson (American)` - true_sol_us) %>% mean()
}

diff <- diff %>% as_tibble() %>% bind_cols(1:(grid_test[,1] %>% length())) %>% arrange(value)
print(diff)
timestep_us <- grid_test[diff[1,2] %>% pull(), 1]
xsteps_us <- grid_test[diff[1, 2] %>% pull(), 2]
cat("Best value: ", "time steps: ", timestep_us , " x steps: ", xsteps_us)
```

## European Replication
```{r}
# Using Crank_Nicolson
spots <- c(36, 38, 40, 42, 44)
S <- c(36, 38, 40, 42, 44); col_names <- c("S", "sigma", "2", "1")
s1 <- Sys.time()
cn_02 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = timestep_eu, x_steps = xsteps_eu, sigma = 0.2, K = 40, spots = spots)
cn_04 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = timestep_eu, x_steps = xsteps_eu, sigma = 0.4, K = 40, spots = spots)
Sys.time() - s1
cn_02 <-  cbind(S, c(rep(0.2, 5)), cn_02)
cn_04 <-  cbind(S, c(rep(0.4, 5)), cn_04)
colnames(cn_02) <- col_names;
colnames(cn_04) <- col_names;
cn_all <- rbind(cn_02, cn_04) %>% 
  as_tibble() %>% 
  arrange(S) %>% 
  tidyr::pivot_longer(cols = c(`1`, `2`), 
                      names_to = "T",
                      values_to = "Finite Difference - Crank Nicolson (European)")

cn_all <- cbind(cn_all, abs(cn_all$`Finite Difference - Crank Nicolson (European)` - true_sol_eu))

print(cn_all)
# xtable::xtable(cn_all, digits = 5) ## LATEX TABLE
```
## American replication
```{r}
spots <- c(36, 38, 40, 42, 44)
S <- c(36, 38, 40, 42, 44); col_names <- c("S", "sigma", "2", "1")

cn_02 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = timestep_us, x_steps = xsteps_us, sigma = 0.2, K = 40, spots = spots)
cn_04 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = timestep_us, x_steps = xsteps_us, sigma = 0.4, K = 40, spots = spots)


cn_02 <-  cbind(S, c(rep(0.2, 5)), cn_02)
cn_04 <-  cbind(S, c(rep(0.4, 5)), cn_04)
colnames(cn_02) <- col_names;
colnames(cn_04) <- col_names;
cn_all <- rbind(cn_02, cn_04) %>% 
  as_tibble() %>% 
  arrange(S) %>% 
  tidyr::pivot_longer(cols = c(`1`, `2`), 
                      names_to = "T",
                      values_to = "Finite Difference - Crank Nicolson (American)") 

cn_all <- cbind(cn_all, abs(cn_all$`Finite Difference - Crank Nicolson (American)` - true_sol_us))

print(cn_all)
# xtable::xtable(cn_all, digits = 3) ## LATEX TABLE
```

# FD2
## Time experiment
```{r, eval = FALSE}

spots <- c(0, 10, 20, 35, 39, 39.9, 40, 40.1, 41, 45, 50, 60, 70, 80, 90, 100)
#spots <- c(36, 38, 40, 42, 44)
time_selections <- c(0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2)
#time_selections <- seq(0, 2, 0.1)

v1 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_eu * 4, x_steps = xsteps_eu * 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v2 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_eu * 4, x_steps = xsteps_eu * 2,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v3 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_eu * 4, x_steps = xsteps_eu,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v4 <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_eu * 2, x_steps = xsteps_eu * 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

cn_acc <- (v1 - v2)/3 + (v1 - v4)/3

############# SIMPLE MC
sims <- c()
t_time <- rep(0, 10)
count <- 1
a_t <- matrix(0, nrow = 6, ncol = 4)
for(i in c(1e+6, 1e+7, 5e+7, 1e+8, 5e+8)){
  t1 <- Sys.time()
  temp <- antithetic_call_put_mc(n_sim=i, Tt=1, r=0.06, sigma=0.2, S0=36, K=40)
  a_t[count, 3] <- temp$price
  a_t[count, 4] <- temp$mc_sd
  a_t[count, 2] <- Sys.time() - t1
  a_t[count, 1] <- i
  count <- count + 1
  cat(i, "\n")
}

##############
t_time <- matrix(0, nrow = 4, ncol = 10)
c_col <- 0 
for(j in c(1e+7, 1e+8, 1e+9, 1e+10)){
  c_col <- c_col + 1
  c_row <- 0
  for(i in c(1e-3, 1e-4, 1e-5)){
  c_row <- c_row + 1
  #t1 <- Sys.time()
    t_time[c_row, c_col] <- system.time(simulate_mc(S0 = 50, K = 40, Tt = 1, sigma = 0.2, 
                                      r = 0.06, acc_measure = i, n_sim = j))[3]
    cat(t_time[c_row, c_col], "\n")
  }
  #t_time[j] <- total_time <- Sys.time() - t1
}

to_table <- t_time %>% as.matrix() %>% cbind(1:10 * 10000000)
colnames(to_table) <- c("Seconds", "Batch size")
#xtable::xtable(to_table)
```
## Comparing absolute errors from table 
```{r, eval = FALSE}
#set.seed(6)
mcerr <- rep(0, 20)
time_used <- system.time(for(i in 1:20){
  mcerr[i] <- simulate_mc(S0 = cn_all$S[i], K = 40, Tt = cn_all$T[i] %>% as.numeric(), sigma = cn_all$sigma[i], 
              r = 0.06, acc_measure = cn_all[i,5], n_sim = 100, 
              err_type = 2, true_sol = true_sol_eu[i])$acc
  cat(i, "\n")
}
)

#xtable::xtable(cn_all[,c(1:3,5)] %>% cbind(mcerr %>% round(5)), digits = 5)
```

# FD3
## Convergence of dx
```{r}
time_steps_us <- 300; x_steps_us <- 1000;
spots <- c(0, 10, 20, 35, 39.9, 40, 40.1, 45, 50, 60, 70, 80, 90, 100)
time_selections <- c(0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2)

v1 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_us * 4, x_steps = xsteps_us * 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v2 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_us * 4, x_steps = xsteps_us * 4 / 2,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v3 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_us * 4, x_steps = xsteps_us * 4 / 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v4 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_us * 4 / 2, x_steps = xsteps_us * 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)

v5 <- crank_nicolson_us(r = 0.06, Tt = 2, x_min = 0, x_max = 100,
                        time_steps = timestep_us * 4 / 4, x_steps = xsteps_us * 4,
                        sigma = 0.2, K = 40, spots = spots, selected_times = time_selections)


x_err <- (v2 - v3) / (v1 - v2)
#xtable::xtable(x_err)

t_err <- (v4 - v5) / (v1 - v4)
#xtable::xtable(t_err)
```
# FD5
## Plots using Dupire
```{r}
dt2 <- 2 / 800
grid_time2 <- seq(0, dt2 * 800, dt2)
dx <- 100 / 1400
grid_x <- seq(0, dx * 1400, dx)

cn_02_2_call <- crank_nicolson_eu(r = 0.06, Tt = 2, x_min = 0, x_max = 100, 
                        time_steps = 800, x_steps = 1400, 
                        sigma = 1.7, K = 40, gamma = 0.5, dupire = T, selected_times = c(2, 1), spots = grid_x)

if(params$save_plots == TRUE){
  png("fd5fig1.png", width = 1200, height = 600)
}
par(mfrow=c(1,2))
plot(grid_x, cn_02_2_call[, 1], type = 'l', xlab = 'Strike', ylab = 'Price', 
     main = 'Call options', xlim = c(0, 100), ylim = c(0, 40)) + 
  lines(grid_x, cn_02_2_call[, 2], type = 'l', col = "red")
legend(60, 40, legend=c("T = 1", "T = 2"),
       col=c("black", "red"), lty=1, cex=1.8)

cn_put_1 <- grid_x * exp(-0.06) + cn_02_2_call[, 1] - 40
cn_put_2 <- grid_x * exp(-0.06*2) + cn_02_2_call[, 2] - 40

plot(grid_x, cn_put_1, type = 'l', xlab = 'Strike', ylab = 'Price', 
     main = 'Put options', xlim = c(0, 100), ylim = c(0, 60)) + 
  lines(grid_x, cn_put_2, type = 'l', col = "red")
legend(1, 60, legend=c("T = 1", "T = 2"),
       col=c("black", "red"), lty=1, cex=1.8)
if(params$save_plots == TRUE){
  dev.off()
}

```

