---
title: "Computational Finance Assignment II"
author: "Lucas Johan Boesen"
date: Sys.Date()
output: html_document
params:
  save_plots: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(dplyr)
library(matlib)
source(paste0(getwd(), "/helper_functions_sim.R"))
```
# S.1
## S.1 - Figure 2
```{r, fig.width = 3, fig.height = 3}
set.seed(3)

K <- 1
d <- 1
Tt <- 1
sigma <- 0.2
num_ite <- 10000
call_prices <- c(rep(0, num_ite))
rand_norm_0 <- rnorm(num_ite)
rand_norm_T <- rnorm(num_ite)

# Simulated call prices
S_0 <- K + d * sigma * sqrt(Tt) * rand_norm_0
S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
S_T <- S_0 + sigma * sqrt(Tt) * rand_norm_T

call_prices <- sapply(S_T, FUN = function(x)max(x - K, 0))

# LM
call_simulations <- cbind(S_0, call_prices) %>% 
  as_data_frame()
est_pricing_func <- lm(call_prices ~ poly(S_0, 7, raw=TRUE), data = call_simulations)

# True pricing function
true_pricing_function <- function(S0, Tt, K, sigma){
  d <- (S0-K)/(sigma*Tt)
  return((S0-K)*pnorm(d)+sigma*sqrt(Tt)*dnorm(d))
}

true_prices <- true_pricing_function(S_0, Tt, K, sigma)
S_0_to_plot <- S_0 
if(params$save_plots == TRUE){
  png("s1fig2.png", width = 1200, height = 600)
}
par(mfrow=c(1,2))
plot(x = S_0, y = call_prices, 
       col = 'grey',
       ylab = "Call value",
       xlab = "Stock price") + 
    lines(S_0_to_plot, 
          est_pricing_func$fitted.values, col = 'red', type = 'l') + 
    lines(S_0_to_plot, 
          true_prices, 
          type = 'l')

derr_pricing_func_val <- est_derr_pricing_function(est_pricing_func$coefficients[-1],
                                                    S_0_to_plot)
# actual derrivatives
true_derr <- pnorm((S_0-K)/(sigma * sqrt(Tt)))

plot(S_0_to_plot, 
  derr_pricing_func_val, 
  type = 'l',
  col = 'red',
  ylab = "Call Delta",
  xlab = "Stock price", add = TRUE) + 
  lines(S_0_to_plot,
        true_derr)
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.1 - Figure 3
```{r, fig.width = 3, fig.height = 3}
plot_index <- S_0_to_plot %>% as_tibble() %>% filter(value < 0.5)

f_w_05 <- calculate_delta(S_0, sigma, 1, 0.5)

f_w_0 <- calculate_delta(S_0, sigma, 1, 1e-12)


remove_from_plot <- -c(seq(dim(plot_index)[1]))
if(params$save_plots == TRUE){
  png("s1fig3.png", width = 800, height = 800)
}
plot(y = f_w_05$D, 
        x = S_0_to_plot, col = "grey", type = "p",
     xlim = c(0.2, 1.7), ylim = c(-0.1, 1.3), 
     xlab=("Stock price"), ylab=("Call Delta"), title = ("Est"))
text(4, 9, "True Delta")+ 
  lines(S_0_to_plot[remove_from_plot],
       true_derr[remove_from_plot], col = "black")+ 
  lines(y = f_w_05$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], type = 'l', col = "red") +
  lines(S_0_to_plot[remove_from_plot], 
  derr_pricing_func_val[remove_from_plot], col = "blue") + 
  lines(y = f_w_0$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], col = "orange")
text(0.22, 0.8, "Black: True Delta", col = "black", adj = 0)
text(0.22, 0.75, "Blue: Price only-regression", col = "blue", adj = 0)
text(0.22, 0.7, "Red: Half/half-regression", col = "red", adj = 0)
text(0.22, 0.65, "Orange: Delta only-regression", col = "orange", adj = 0)
text(0.22, 1.2, "Grey o's: Simulated Deltas", col = "grey", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.1 - Figure 4
```{r, warning = FALSE, message = FALSE}
seed <- 42
K <- 1; Tt <- 1; sigma <- 0.2; dt <- 1/52; num_rep <- 1000; w <- 0.5;batch_size <- 1; d <- 1
simulations <- c(400, 600, 1000, 2000, 3000, 4000, 5000, 6000)
true_delta_err <- w_05_delta_err_7 <- matrix(c(rep(0, length(simulations)*batch_size)), ncol = length(simulations))
pricing_delta_err_3 <- w_05_delta_err_3 <- w_05_delta_err_7
pricing_delta_err_4 <- w_05_delta_err_4 <- w_05_delta_err_7
pricing_delta_err_5 <- w_05_delta_err_5 <- w_05_delta_err_7
pricing_delta_err_6 <- w_05_delta_err_6 <- w_05_delta_err_7
pricing_delta_err_7 <- w_05_delta_err_7 <- w_05_delta_err_7
pricing_delta_err_8 <- w_05_delta_err_8 <- w_05_delta_err_7
pricing_delta_err_9 <- w_05_delta_err_9 <- w_05_delta_err_7
initial_price <- ZeroRateBachelierCall(1, Tt, K, sigma)$Price
for(j in 1:batch_size){
  for(i in 1:length(simulations)){
    set.seed(j)
    num_sim <- simulations[i]
    St <- c(rep(1, num_rep))
    rand_norm_0 <- rnorm(num_sim)
    S_0 <- K + d * sigma * sqrt(Tt) * rand_norm_0

    ### Calculating true delta hedge error
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, true_delta, pol_degree = 7, seed = seed)
    true_delta_err[j, i] <- err / initial_price
    
    ### Calculating using w = 0.5 
    coefs <- NULL
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 delta_func = calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 4, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_4[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 5, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_5[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 6, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_6[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 7, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_7[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 9, w = 0.5, seed = seed, coefs = coefs)
    w_05_delta_err_9[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 3, seed = seed)
    pricing_delta_err_3[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 4, seed = seed)
    pricing_delta_err_4[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 5, seed = seed)
    pricing_delta_err_5[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 6, seed = seed)
    pricing_delta_err_6[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 7, seed = seed)
    pricing_delta_err_7[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 8, seed = seed)
    pricing_delta_err_8[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, calculate_delta_price, pol_degree = 9, seed = seed)
    pricing_delta_err_9[j, i] <- err / initial_price
    
  }
}
```

## S.1 - Figure 4 plot
```{r}
true_delta_err_mean <- colMeans(true_delta_err)
w_05_delta_err_3_mean <- colMeans(w_05_delta_err_3)
pricing_delta_err_3_mean <- colMeans(pricing_delta_err_3)
w_05_delta_err_4_mean <- colMeans(w_05_delta_err_4)
pricing_delta_err_4_mean <- colMeans(pricing_delta_err_4)
w_05_delta_err_5_mean <- colMeans(w_05_delta_err_5)
pricing_delta_err_5_mean <- colMeans(pricing_delta_err_5)
w_05_delta_err_6_mean <- colMeans(w_05_delta_err_6)
pricing_delta_err_6_mean <- colMeans(pricing_delta_err_6)
w_05_delta_err_7_mean <- colMeans(w_05_delta_err_7)
pricing_delta_err_7_mean <- colMeans(pricing_delta_err_7)
w_05_delta_err_8_mean <- colMeans(w_05_delta_err_8)
pricing_delta_err_8_mean <- colMeans(pricing_delta_err_8)
w_05_delta_err_9_mean <- colMeans(w_05_delta_err_9)
pricing_delta_err_9_mean <- colMeans(pricing_delta_err_9)

if(params$save_plots == TRUE){
  png("s1fig4.png", width = 1000, height = 800)
}
plot(y = true_delta_err_mean, simulations, type = 'l', lty = 0, 
     ylim = c(0.09, 0.4), xlim = c(0, 6000), col = "red",
     xlab = "Standard deviation of relative hedge error", ylab = "#simulations") +
  lines(y = pricing_delta_err_3_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_4_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_5_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_6_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_7_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_8_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_9_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = w_05_delta_err_3_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_4_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_5_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_6_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_7_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_8_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_9_mean, x = simulations, type = 'b', col = "blue") +
abline(v = 6000)
text(2000, 0.4, "Orange curves: Price only-regression", adj = 0, col = "orange", cex = 2)
text(2000, 0.385, "Blue curves: (Price, Delta)-regression", adj = 0, col = "blue", cex = 2)
abline(h = true_delta_err_mean[1], col = "red", lty = 2)
text(0, true_delta_err[1]*1.05, paste0("Heding with true Delta"), col = "red", adj = 0)
# text(6100, pricing_delta_err_3[8], paste0("3"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_4[8], paste0("4"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_5[8], paste0("5"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_6[8], paste0("6"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_7[8], paste0("7"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_8[8], paste0("8"), col = "orange", adj = 0)
# text(6100, pricing_delta_err_9[8], paste0("9"), col = "orange", adj = 0)
text(6100, w_05_delta_err_3[8], paste0("3"), col = "blue", adj = 0)
text(6100, w_05_delta_err_4[8], paste0("4"), col = "blue", adj = 0)
text(6150, w_05_delta_err_5[8], paste0("5"), col = "blue", adj = 0)
text(6100, w_05_delta_err_6[8], paste0("6"), col = "blue", adj = 0)
text(6150, w_05_delta_err_7[8], paste0("7"), col = "blue", adj = 0)
text(6100, w_05_delta_err_8[8], paste0("8"), col = "blue", adj = 0)
text(6150, w_05_delta_err_9[8], paste0("9"), col = "blue", adj = 0)
text(0, 0, "K = 1, T = 1, vol = 0.2, dt = 1/52, #repetitions = 1000", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

# S.2
## S.2 - Figure 2
```{r, fig.width = 3, fig.height = 3}
set.seed(1)

K <- 1
d <- 1
Tt <- 1
sigma <- 0.2
num_ite <- 10000
call_prices <- c(rep(0, num_ite))
rand_norm_0 <- rnorm(num_ite)
rand_norm_T <- rnorm(num_ite)

# Simulated call prices
S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_T)
S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
S_T <- S_0 * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_T)

call_prices <- sapply(S_T, FUN = function(x)max(x - K, 0))

# LM
call_simulations <- cbind(S_0, call_prices) %>% 
  as_data_frame()
est_pricing_func <- lm(call_prices ~ poly(S_0, 7, raw=TRUE), data = call_simulations)

# True pricing function
true_prices <- BS_func(S_0, K, sigma, Tt)$Price
S_0_to_plot <- S_0 
if(params$save_plots == TRUE){
  png("s2fig2.png", width = 1200, height = 600)
}
par(mfrow=c(1,2))
plot(x = S_0, y = call_prices, 
       col = 'grey',
       ylab = "Call value",
       xlab = "Stock price") + 
    lines(S_0_to_plot, 
          est_pricing_func$fitted.values, col = 'red', type = 'l') + 
    lines(S_0_to_plot, 
          true_prices, 
          type = 'l')+ 
  title("Black Scholes")

derr_pricing_func_val <- est_derr_pricing_function(est_pricing_func$coefficients[-1],
                                                    S_0_to_plot)
# actual derrivatives
d1 <- (log(S_0 / K) + (1/2 * sigma^2) * Tt) / (sigma * Tt)
true_derr <- pnorm(d1)

plot(S_0_to_plot, 
  derr_pricing_func_val, 
  type = 'l',
  col = 'red',
  ylab = "Call Delta",
  xlab = "Stock price", add = TRUE) + 
  lines(S_0_to_plot,
        true_derr) + 
  title("Black Scholes")
if(params$save_plots == TRUE){
  dev.off()
}
```
## S.2 - Figure 3
```{r, fig.width = 3, fig.height = 3}
plot_index <- S_0_to_plot %>% as_tibble() %>% filter(value < 0.5)

f_w_05 <- calculate_delta(S_0, sigma, 1, 0.5, BS = TRUE)

f_w_0 <- calculate_delta(S_0, sigma, 1, 1e-12, BS = TRUE)

remove_from_plot <- -c(seq(dim(plot_index)[1]))
if(params$save_plots == TRUE){
  png("s2fig3.png", width = 800, height = 800)
}
plot(y = f_w_05$D, 
        x = S_0_to_plot, col = "grey", type = "p",
     #xlim = c(0.2, 1.7), ylim = c(-0.1, 1.3), 
     xlab=("Stock price"), ylab=("Call Delta"), title = ("Est"))
text(4, 9, "True Delta")+ 
  lines(S_0_to_plot[remove_from_plot],
       true_derr[remove_from_plot], col = "black")+ 
  lines(y = f_w_05$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], type = 'l', col = "red") +
  lines(S_0_to_plot[remove_from_plot], 
  derr_pricing_func_val[remove_from_plot], col = "blue") + 
  lines(y = f_w_0$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], col = "orange")
text(0.5, 0.8, "Black: True Delta", col = "black", adj = 0)
text(0.5, 0.75, "Blue: Price only-regression", col = "blue", adj = 0)
text(0.5, 0.7, "Red: Half/half-regression", col = "red", adj = 0)
text(0.5, 0.65, "Orange: Delta only-regression", col = "orange", adj = 0)
text(0.5, 1.8, "Grey o's: Simulated Deltas", col = "grey", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.2 - Figure 4
```{r, warning = FALSE, message = FALSE}
seed <- 42
K <- 1; Tt <- 1; sigma <- 0.2; dt <- 1/52; num_rep <- 1000; w <- 0.5;batch_size <- 1
simulations <- c(400, 600, 1000, 2000, 3000, 4000, 5000, 6000)
true_delta_err <- w_05_delta_err_7 <- matrix(c(rep(0, length(simulations)*batch_size)), ncol = length(simulations))
pricing_delta_err_3 <- w_05_delta_err_3 <- w_05_delta_err_7
pricing_delta_err_4 <- w_05_delta_err_4 <- w_05_delta_err_7
pricing_delta_err_5 <- w_05_delta_err_5 <- w_05_delta_err_7
pricing_delta_err_6 <- w_05_delta_err_6 <- w_05_delta_err_7
pricing_delta_err_7 <- w_05_delta_err_7 <- w_05_delta_err_7
pricing_delta_err_8 <- w_05_delta_err_8 <- w_05_delta_err_7
pricing_delta_err_9 <- w_05_delta_err_9 <- w_05_delta_err_7
initial_price <- BS_func(St = 1, K = K, sigma = sigma, Tt = Tt)$Price
for(j in 1:batch_size){
  for(i in 1:length(simulations)){
    set.seed(j)
    #seed <- j
    num_sim <- simulations[i]
    St <- c(rep(1, num_rep))
    rand_norm_0 <- rnorm(num_sim)
    S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
    S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()

    ### Calculating true delta hedge error
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 true_delta, pol_degree = 7, seed = seed, BS = TRUE, call_func = BS_func)
    true_delta_err[j, i] <- err / initial_price
    
    ### Calculating using w = 0.5 
    coefs <- NULL
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 4, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_4[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 5, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_5[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 6, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_6[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 7, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_7[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 9, w = 0.5, seed = seed, coefs = coefs, BS = TRUE, call_func = BS_func)
    w_05_delta_err_9[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 3, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_3[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 4, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_4[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 5, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_5[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 6, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_6[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 7, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_7[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 8, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_8[j, i] <- err / initial_price
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta_price, pol_degree = 9, seed = seed, BS = TRUE, call_func = BS_func)
    pricing_delta_err_9[j, i] <- err / initial_price
    
  }
}
```

## S.2 - Figure 4 plot
```{r}
true_delta_err_mean <- colMeans(true_delta_err)
w_05_delta_err_3_mean <- colMeans(w_05_delta_err_3)
pricing_delta_err_3_mean <- colMeans(pricing_delta_err_3)
w_05_delta_err_4_mean <- colMeans(w_05_delta_err_4)
pricing_delta_err_4_mean <- colMeans(pricing_delta_err_4)
w_05_delta_err_5_mean <- colMeans(w_05_delta_err_5)
pricing_delta_err_5_mean <- colMeans(pricing_delta_err_5)
w_05_delta_err_6_mean <- colMeans(w_05_delta_err_6)
pricing_delta_err_6_mean <- colMeans(pricing_delta_err_6)
w_05_delta_err_7_mean <- colMeans(w_05_delta_err_7)
pricing_delta_err_7_mean <- colMeans(pricing_delta_err_7)
w_05_delta_err_8_mean <- colMeans(w_05_delta_err_8)
pricing_delta_err_8_mean <- colMeans(pricing_delta_err_8)
w_05_delta_err_9_mean <- colMeans(w_05_delta_err_9)
pricing_delta_err_9_mean <- colMeans(pricing_delta_err_9)
if(params$save_plots == TRUE){
  png("s2fig4.png", width = 800, height = 600)
}
plot(y = true_delta_err_mean, simulations, type = 'l', lty = 0, 
     xlim = c(0, 6000), ylim = c(0.09, 1), col = "red") +
  lines(y = pricing_delta_err_3_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_4_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_5_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_6_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_7_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_8_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = pricing_delta_err_9_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = w_05_delta_err_3_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_4_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_5_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_6_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_7_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_8_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = w_05_delta_err_9_mean, x = simulations, type = 'b', col = "blue")
text(2000, 0.85, "Orange curves: Price only-regression", adj = 0, col = "orange", cex = 2)
text(2000, 0.8, "Blue curves: (Price, Delta)-regression", adj = 0, col = "blue", cex = 2)
abline(h = true_delta_err_mean[1], col = "red", lty = 2)
text(0, true_delta_err[1]*1.1, paste0("Heding with true Delta"), col = "red", adj = 0)
text(6100, w_05_delta_err_3_mean[8], paste0("3"), col = "blue", adj = 0)
text(6100, w_05_delta_err_4_mean[8], paste0("4"), col = "blue", adj = 0)
text(6150, w_05_delta_err_5_mean[8], paste0("5"), col = "blue", adj = 0)
text(6100, w_05_delta_err_6_mean[8], paste0("6"), col = "blue", adj = 0)
text(6150, w_05_delta_err_7_mean[8], paste0("7"), col = "blue", adj = 0)
text(6100, w_05_delta_err_8_mean[8], paste0("8"), col = "blue", adj = 0)
text(6150, w_05_delta_err_9_mean[8], paste0("9"), col = "blue", adj = 0)
text(0, 0, "K = 1, T = 1, vol = 0.2, dt = 1/52, #repetitions = 1000", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

# S.3
## S.3 - Figure 4
```{r, warning = FALSE, message = FALSE}
seed <- 42
K <- 1; Tt <- 1; sigma <- 0.2; dt <- 1/52; num_rep <- 1000; w <- 0.5;batch_size <- 1
simulations <- c(400, 600, 1000, 2000, 3000, 4000, 5000, 6000)
lrm_3 <- lrm_8 <- std_3 <- std_8 <- matrix(c(rep(0, length(simulations)*batch_size)), ncol = length(simulations))
initial_price <- BS_func(1, K, sigma, Tt)$Price
for(j in 1:batch_size){
  for(i in 1:length(simulations)){
    set.seed(j)
    # seed <- j+11
    #seed <- j
    num_sim <- simulations[i]
    St <- c(rep(1, num_rep))
    rand_norm_0 <- rnorm(num_sim)
    S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
    S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()

    ### Calculating using w = 0.5 
    coefs <- NULL
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = BS_func, LRM = TRUE)
    lrm_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = BS_func, LRM = TRUE)
    lrm_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                             calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs, 
                             BS = TRUE, call_func = BS_func, LRM = FALSE)
    std_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = BS_func, LRM = FALSE)
    std_8[j, i] <- err / initial_price
    
  }
}
```

## S.3 - Figure 4 plot
```{r}
lrm_3_mean <- colMeans(lrm_3)
lrm_8_mean <- colMeans(lrm_8)
std_3_mean <- colMeans(std_3)
std_8_mean <- colMeans(std_8)

if(params$save_plots == TRUE){
  png("s3fig4.png", width = 800, height = 600)
}
plot(y = lrm_3_mean, simulations, type = 'b', ylim = c(0.0, 1), xlim = c(0, 6500), col = "orange",
     ylab = "Standard deviation of relative hedge error", xlab = "#simulations") +
  lines(y = lrm_8_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_3_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = std_8_mean, x = simulations, type = 'b', col = "blue")
abline(h = true_delta_err_mean[1], col = "red", lty = 2)
text(6100, lrm_3_mean[8], paste0("3"), col = "orange", adj = 0)
text(6100, lrm_8_mean[8], paste0("8"), col = "orange", adj = 0)
text(6200, std_3_mean[8], paste0("3"), col = "blue", adj = 0)
text(6200, std_8_mean[8], paste0("8"), col = "blue", adj = 0)
text(0, true_delta_err_mean[1]+0.02, paste0("Heding with true Delta"), col = "red", adj = 0)
text(2000, 0.8, "Orange curves: LRM method", adj = 0, col = "orange")
text(2000, 0.875, "Blue curves: Pathwise method", adj = 0, col = "blue")
text(0, 0, "K = 1, T = 1, vol = 0.2, dt = 1/52, #repetitions = 1000", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

# S.4 
## S.4 - Figure 2
```{r, fig.width = 3, fig.height = 3}
set.seed(3)

K <- 1
d <- 1
Tt <- 1
sigma <- 0.2
num_ite <- 10000
call_prices <- c(rep(0, num_ite))
rand_norm_0 <- rnorm(num_ite)
rand_norm_T <- rnorm(num_ite)

# Simulated call prices
S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
S_T <- S_0 * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_T)

call_prices <- sapply(S_T, FUN = function(x) ifelse(x >= K, 1, 0))

# LM
call_simulations <- cbind(S_0, call_prices) %>% 
  as_data_frame()
est_pricing_func <- lm(call_prices ~ poly(S_0, 7, raw=TRUE), data = call_simulations)

# True pricing function
true_prices <- digital_call(St = S_0, K = K, sigma = sigma, Tt = Tt)$Price
S_0_to_plot <- S_0 
if(params$save_plots == TRUE){
  png("s4fig2.png", width = 1200, height = 600)
}
par(mfrow=c(1,2))
plot(x = S_0, y = call_prices, 
       col = 'grey',
       ylab = "Call value",
       xlab = "Stock price") + 
    lines(S_0_to_plot, 
          est_pricing_func$fitted.values, col = 'red', type = 'l') + 
    lines(S_0_to_plot, 
          true_prices, 
          type = 'l')+ 
  title("Digital Option - Black Scholes")

derr_pricing_func_val <- est_derr_pricing_function(est_pricing_func$coefficients[-1],
                                                    S_0_to_plot)
# actual derrivatives

true_derr <- true_delta(St = S_0, K = K, sigma = sigma, Tt = Tt, BS = TRUE, digital = TRUE)$delta

plot(S_0_to_plot, 
  derr_pricing_func_val, 
  type = 'l',
  col = 'red',
  ylab = "Call Delta",
  xlab = "Stock price", add = TRUE) + 
  lines(S_0_to_plot,
        true_derr) + 
  title("Digital Option - Black Scholes")
if(params$save_plots == TRUE){
  dev.off()
}
```
## S.4 - Figure 3
```{r, fig.width = 3, fig.height = 3}
plot_index <- S_0_to_plot %>% as_tibble() %>% filter(value < 0.5)

f_w_05 <- calculate_delta(S_0, sigma, 1, 0.5, BS = TRUE, digital = TRUE, LRM = TRUE)

f_w_0 <- calculate_delta(S_0, sigma, 1, 1e-12, BS = TRUE, digital = TRUE, LRM = TRUE)

remove_from_plot <- -c(seq(dim(plot_index)[1]))
if(params$save_plots == TRUE){
  png("s4fig3.png", width = 800, height = 800)
}
plot(y = f_w_05$D, 
        x = S_0_to_plot, col = "grey", type = "p",
     #xlim = c(0.2, 1.7), ylim = c(-0.1, 1.3), 
     xlab=("Stock price"), ylab=("Call Delta"), title = ("Est"), ylim = c(-2, 15), xlim = c(0.1, 2.1))
text(4, 9, "True Delta")+ 
  lines(S_0_to_plot[remove_from_plot],
       true_derr[remove_from_plot], col = "black")+ 
  lines(y = f_w_05$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], type = 'l', col = "red") +
  lines(S_0_to_plot[remove_from_plot], 
  derr_pricing_func_val[remove_from_plot], col = "blue") + 
  lines(y = f_w_0$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], col = "orange")
text(0.22, 10, "Black: True Delta", col = "black", adj = 0)
text(0.22, 9, "Blue: Price only-regression", col = "blue", adj = 0)
text(0.22, 8, "Red: Half/half-regression", col = "red", adj = 0)
text(0.22, 7, "Orange: Delta only-regression", col = "orange", adj = 0)
text(0.22, 13, "Grey o's: Simulated Deltas", col = "grey", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```
## S.4 - Figure 4
```{r, warning = FALSE, message = FALSE}
seed <- 43
K <- 1; Tt <- 1; sigma <- 0.2; dt <- 1/52; num_rep <- 1000; w <- 0.5;batch_size <- 10
simulations <- c(400, 600, 1000, 2000, 3000, 4000, 5000, 6000)
true_delta_err <- delta_lrm_3 <- delta_lrm_8 <- std_3 <- std_8 <- matrix(c(rep(0, length(simulations)*batch_size)), ncol = length(simulations))
delta_lrm_5 <- delta_lrm_7 <- delta_lrm_3
std_7 <- std_5 <- std_3 
initial_price <- digital_call(St = 1, K = K, sigma = sigma, Tt = Tt)$Price
for(j in 1:batch_size){
  for(i in 1:length(simulations)){
    set.seed(j)
    #seed <- j+11
    #seed <- j
    num_sim <- simulations[i]
    St <- c(rep(1, num_rep))
    rand_norm_0 <- rnorm(num_sim)
    S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
    S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 true_delta, pol_degree = 7, seed = seed, BS = TRUE, 
                                 call_func = digital_call, digital = TRUE, LRM = TRUE)
    true_delta_err[j, i] <- err / initial_price
    
    ### Calculating using w = 0.5 
    coefs <- NULL
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE)
    delta_lrm_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE)
    delta_lrm_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 5, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE)
    delta_lrm_5[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 7, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE)
    delta_lrm_7[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 3, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_3[j, i] <- err / initial_price

    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 8, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 5, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_5[j, i] <- err / initial_price

    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 7, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_7[j, i] <- err / initial_price
    
  }
}
```

## S.4 - Figure 4 plot
```{r}
delta_lrm_3_mean <- colMeans(delta_lrm_3)
delta_lrm_8_mean <- colMeans(delta_lrm_8)
std_3_mean <- colMeans(std_3)
std_8_mean <- colMeans(std_8)
delta_lrm_5_mean <- colMeans(delta_lrm_5)
delta_lrm_7_mean <- colMeans(delta_lrm_7)
std_5_mean <- colMeans(std_5)
std_7_mean <- colMeans(std_7)
true_delta_err_mean <- colMeans(true_delta_err)

if(params$save_plots == TRUE){
  png("s4fig4.png", width = 800, height = 600)
}
plot(y = delta_lrm_3_mean, simulations, type = 'b', ylim = c(0.0, 1), xlim = c(0, 6500), col = "blue",
     ylab = "Standard deviation of relative hedge error", xlab = "#simulations") +
  lines(y = delta_lrm_8_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = delta_lrm_5_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = delta_lrm_7_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = delta_lrm_8_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = std_3_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_5_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_7_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_8_mean, x = simulations, type = 'b', col = "orange")
abline(h = true_delta_err_mean[1], col = "red", lty = 2)
text(6100, delta_lrm_3_mean[8], paste0("3"), col = "blue", adj = 0)
text(6100, delta_lrm_8_mean[8], paste0("8"), col = "blue", adj = 0)
text(6200, std_3_mean[8], paste0("3"), col = "orange", adj = 0)
text(6200, std_8_mean[8], paste0("8"), col = "orange", adj = 0)
text(0, true_delta_err_mean[1]+0.02, paste0("Heding with true Delta"), col = "red", adj = 0)
text(2000, 0.8, "Orange curves: Price only-regression", adj = 0, col = "orange")
text(2000, 0.875, "Blue curves: (Price, Delta)-regression", adj = 0, col = "blue")
text(0, 0, "K = 1, T = 1, vol = 0.2, dt = 1/52, #repetitions = 1000", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```
# S.5
## Finding optimal epsilon
```{r}
# Minimizing variance
#S_0 <- 100; sigma <- 0.3;r <- 0.05;K <- 100
S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
S_T <- S_0 * exp((1/2 * sigma^2) * Tt + sigma * sqrt(Tt) * rand_norm_T)
rand_norm_eps <- rnorm(length(S_T))

delta_func <- function(eps){
  return(var(calculate_delta(S_0, sigma, 1, 0.5, BS = TRUE, digital = TRUE, 
                             LRM = T, MM = TRUE, eps = eps, setseed = T)$D))
}

delta_var <- c(rep(0, 500))
eps_seq <- c(seq(0.001, 10, 10/500))
for(i in 1:500){
  delta_var[i] <- delta_func(eps_seq[i])
}

min_delta <- delta_var %>% as_tibble() %>% 
  bind_cols(eps_seq) %>% arrange(value) %>% slice(1)
if(params$save_plots == TRUE){
  png("s5figeps.png", width = 800, height = 800)
}
plot(delta_var[-1], x = eps_seq[-1], xlim = c(.22, 10), type = 'l', col = "red",
     xlab = "Variance of D") +
abline(v = min_delta$...2)
text(min_delta$...2, min_delta$value*3, paste0("Optimal eps = ", min_delta$...2), adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.5 - Figure 2
```{r, fig.width = 3, fig.height = 3}
set.seed(3)

K <- 1
d <- 1
Tt <- 1
sigma <- 0.2
num_ite <- 10000
call_prices <- c(rep(0, num_ite))
rand_norm_0 <- rnorm(num_ite)
rand_norm_T <- rnorm(num_ite)
eps <- min_delta$...2

# Simulated call prices
S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_T)
S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
S_T <- S_0 * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_T)

#call_prices_mm <- sapply(S_T, FUN = function(x) min(1, max(0, (x - K + eps))/(2*eps)))
call_prices <- sapply(S_T, FUN = function(x) ifelse(x >= K, 1, 0))

# LM
call_simulations <- cbind(S_0, call_prices) %>% 
  as_data_frame()
est_pricing_func <- lm(call_prices ~ poly(S_0, 7, raw=TRUE), data = call_simulations)

# True pricing function
true_prices <- digital_call(St = S_0, K = K, sigma = sigma, Tt = Tt)$Price
S_0_to_plot <- S_0 
if(params$save_plots == TRUE){
  png("s5fig2.png", width = 1200, height = 600)
}
par(mfrow=c(1,2))
plot(x = S_0, y = call_prices, 
       col = 'grey',
       ylab = "Call value",
       xlab = "Stock price") + 
    lines(S_0_to_plot, 
          est_pricing_func$fitted.values, col = 'red', type = 'l') + 
    lines(S_0_to_plot, 
          true_prices, 
          type = 'l')+ 
  title("Digital Option - Mixed Method")

derr_pricing_func_val <- est_derr_pricing_function(est_pricing_func$coefficients[-1],
                                                    S_0_to_plot)
# actual derrivatives

true_derr <- true_delta(St = S_0, K = K, sigma = sigma, Tt = Tt, BS = TRUE, digital = TRUE)$delta

plot(S_0_to_plot, 
  derr_pricing_func_val, 
  type = 'l',
  col = 'red',
  ylab = "Call Delta",
  xlab = "Stock price", add = TRUE) + 
  lines(S_0_to_plot,
        true_derr) + 
  title("Digital Option - Mixed Method")
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.5 - Figure 3
```{r, fig.width = 3, fig.height = 3}
plot_index <- S_0_to_plot %>% as_tibble() %>% filter(value < 0.5)

f_w_05 <- calculate_delta(S_0, sigma, 1, 0.5, BS = TRUE, digital = TRUE, LRM = TRUE, MM = TRUE, eps = eps)

f_w_0 <- calculate_delta(S_0, sigma, 1, 1e-12, BS = TRUE, digital = TRUE, LRM = TRUE, MM = TRUE, eps = eps)

remove_from_plot <- -c(seq(dim(plot_index)[1]))
if(params$save_plots == TRUE){
  png("s5fig3.png", width = 800, height = 800)
}
plot(y = f_w_05$D, 
        x = S_0_to_plot, col = "grey", type = "p",
     #xlim = c(0.2, 1.7), ylim = c(-0.1, 1.3), 
     xlab=("Stock price"), ylab=("Call Delta"), title = ("Est"), ylim = c(-2, 15), xlim = c(0.1, 2.1))
text(4, 9, "True Delta")+ 
  lines(S_0_to_plot[remove_from_plot],
       true_derr[remove_from_plot], col = "black")+ 
  lines(y = f_w_05$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], type = 'l', col = "red") +
  lines(S_0_to_plot[remove_from_plot], 
  derr_pricing_func_val[remove_from_plot], col = "blue") + 
  lines(y = f_w_0$delta[remove_from_plot], 
        x = S_0_to_plot[remove_from_plot], col = "orange")
text(0.22, 10, "Black: True Delta", col = "black", adj = 0)
text(0.22, 9, "Blue: Price only-regression", col = "blue", adj = 0)
text(0.22, 8, "Red: Half/half-regression", col = "red", adj = 0)
text(0.22, 7, "Orange: Delta only-regression", col = "orange", adj = 0)
text(0.22, 13, "Grey o's: Simulated Deltas", col = "grey", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```

## S.5 - Figure 4
```{r, warning = FALSE, message = FALSE}
seed <- 43
K <- 1; Tt <- 1; sigma <- 0.2; dt <- 1/52; num_rep <- 1000; w <- 0.5;batch_size <- 10
simulations <- c(400, 600, 1000, 2000, 3000, 4000, 5000, 6000)
true_delta_err <- delta_lrm_3 <- delta_lrm_8 <- std_3 <- std_8 <- matrix(c(rep(0, length(simulations)*batch_size)), ncol = length(simulations))
delta_lrm_5 <- delta_lrm_7 <- delta_lrm_3
std_5 <- std_7 <- std_3
initial_price <- digital_call(St = 1, K = K, sigma = sigma, Tt = Tt)$Price
for(j in 1:batch_size){
  for(i in 1:length(simulations)){
    set.seed(j)
    # seed <- j+11
    #seed <- j
    num_sim <- simulations[i]
    St <- c(rep(1, num_rep))
    rand_norm_0 <- rnorm(num_sim)
    S_0 <- K * exp(-1/2 * sigma^2 * Tt + sigma * sqrt(Tt) * rand_norm_0)
    S_0 <- S_0 %>% as_tibble() %>% arrange(value) %>% pull()
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 true_delta, pol_degree = 7, seed = seed, BS = TRUE, 
                                 call_func = digital_call, digital = TRUE, LRM = TRUE)
    true_delta_err[j, i] <- err / initial_price
    
    ### Calculating using w = 0.5 
    coefs <- NULL
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 3, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE, MM = TRUE, eps = eps)
    delta_lrm_3[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 8, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE, MM = TRUE, eps = eps)
    delta_lrm_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 5, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE, MM = TRUE, eps = eps)
    delta_lrm_5[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0, 
                                 calculate_delta, pol_degree = 7, w = 0.5, seed = seed, coefs = coefs, 
                                 BS = TRUE, call_func = digital_call, LRM = TRUE, digital = TRUE, MM = TRUE, eps = eps)
    delta_lrm_7[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 3, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_3[j, i] <- err / initial_price

    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 8, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_8[j, i] <- err / initial_price
    
    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 7, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_5[j, i] <- err / initial_price

    err <- calculate_hedge_error(dt, Tt, num_rep, K, sigma, St, S0 = S_0,
                                 calculate_delta_price, pol_degree = 7, w = 1, seed = seed, coefs = coefs,
                                 BS = TRUE, call_func = BS_func, LRM = FALSE, digital = TRUE)
    std_7[j, i] <- err / initial_price
    
  }
}
```

## S.5 - Figure 4 plot
```{r}
lrm_3_mean <- colMeans(delta_lrm_3)
lrm_8_mean <- colMeans(delta_lrm_8)
std_3_mean <- colMeans(std_3)
std_8_mean <- colMeans(std_8)
lrm_5_mean <- colMeans(delta_lrm_5)
lrm_7_mean <- colMeans(delta_lrm_7)
std_5_mean <- colMeans(std_5)
std_7_mean <- colMeans(std_7)
true_delta_err_mean <- colMeans(true_delta_err)

if(params$save_plots == TRUE){
  png("s5fig4.png", width = 800, height = 600)
}
plot(y = lrm_3_mean, simulations, type = 'b', ylim = c(0.0, 1), xlim = c(0, 6500), col = "blue",
     ylab = "Standard deviation of relative hedge error", xlab = "#simulations") +
  lines(y = lrm_5_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = lrm_7_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = lrm_8_mean, x = simulations, type = 'b', col = "blue")+
  lines(y = std_3_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_5_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_7_mean, x = simulations, type = 'b', col = "orange")+
  lines(y = std_8_mean, x = simulations, type = 'b', col = "orange")
abline(h = true_delta_err_mean[1], col = "red", lty = 2)
text(6100, lrm_3_mean[8], paste0("3"), col = "blue", adj = 0)
text(6100, lrm_8_mean[8], paste0("8"), col = "blue", adj = 0)
text(6200, std_3_mean[8], paste0("3"), col = "orange", adj = 0)
text(6200, std_8_mean[8], paste0("8"), col = "orange", adj = 0)
text(0, true_delta_err_mean[1]+0.02, paste0("Heding with true Delta"), col = "red", adj = 0)
text(2000, 0.8, "blue curves: (Price, Delta)-regression", adj = 0, col = "blue")
text(2000, 0.875, "orange curves: Price only-regression", adj = 0, col = "orange")
text(0, 0, "K = 1, T = 1, vol = 0.2, dt = 1/52, #repetitions = 1000", adj = 0)
if(params$save_plots == TRUE){
  dev.off()
}
```